apps:
  log_level: "DEBUG"
  rest:
    port: 8080
    jwt:
      validation_url: "https://api.camelot.icerzack.space/api/v1/users/me"
      header_name: "X-Auth-Token"

storage:
  users:
    type: "in-memory"
  rooms:
    type: "in-memory"
