apps:
  log_level: "DEBUG"
  rest:
    port: 8080
    validation:
      jwt_header_name: "X-Auth-Token"
      jwt_url: "https://api-stg.camelot.icerzack.space/api/v1/users/about/me"
      board_url: "https://api-stg.camelot.icerzack.space/api/v1/boards"

storage:
  users:
    type: "in-memory"
  rooms:
    type: "in-memory"
