version: "3.8"

services:
  app:
    image: icerzack/excaliroom:latest
    platform: linux/amd64
    environment:
      - CONFIG_PATH=config.yaml
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/config.yaml