version: "3.8"

services:
  app:
    build:
        context: .
        dockerfile: build/Dockerfile
    environment:
      - CONFIG_PATH=config.yaml
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/config.yaml